'''
Assignment : 6 Create a program that will play the cows and bulls game with the user. The game works like this:

Step 1: Randomly generate a 4-digit number.
Step 2: Ask the user to guess a 4-digit number.
Step 3: For every digit that the user guessed correctly in the correct place, they have a cow.
Step 4: For every digit the user guessed correctly in the wrong place is a bull.

Every time the user makes a guess, tell them how many cows and bulls they have. Once the user guesses the correct
number, the game is over.
Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
   1234
  2 cows, 0 bulls
   1256
  1 cow, 1 bull
  ...

Until the user guesses the number.
'''


def clue(hidden_word, user_guess):
    guess_word_list = list(user_guess)
    hidden_word_list = list(hidden_word)
    matched_word = list()
    position = list()
    match_word_position = list()

    for Char in guess_word_list:
        if Char in hidden_word_list:  # if Char in guess word presents in word list of hidden word.
            matched_word.append(Char)   # matched word is stored.
            index = guess_word_list.index(Char)
            position.append(index)    # position of matched word is stored.

        else:
            matched_word.append(' ')   # unmatched word is ' '.
            index = guess_word_list.index(Char)
            position.append(index)    # position of matched word is stored.


    for pos in position:
        if hidden_word_list[pos] == matched_word[pos]:      # Position wise matching.
            match_word_position.append(matched_word[pos])   # add position wise matched char.

    count_cow = 0
    count_bull = 0
    clue_word = ''
    for Char in user_guess:
        if Char in match_word_position:
            count_cow += 1
        if Char not in match_word_position and Char in matched_word:
            count_bull += 1

    if count_cow > 0:
        clue_word = clue_word + str(count_cow) + " Cow, "
    else:
        clue_word = clue_word + str(count_cow) + " Cows, "
    if count_bull > 0:
        clue_word = clue_word + str(count_bull) + " bull"
    else:
        clue_word = clue_word + str(count_bull) + " bulls"

    del guess_word_list
    del hidden_word_list
    del matched_word
    del position
    del match_word_position

    return clue_word

print("\tWelcome to the Cows and Bulls Game !!")
print("There is a hidden number, four characters long and your need to in few attempts as possible.\n")
print("\t Guess First then you get two clues such as :- \n 1. For every digit that the user guessed correctly in the correct place, they have a cow.\n")
print(" 2.For every digit the user guessed correctly in the wrong place is a bull.\n\n")

hidden_word = "1038"
guess = raw_input("Guess the hidden number:: ")
word_clue = clue(hidden_word, guess)
print word_clue
tries = 1
option_flag = False
# Selected Color guessing loop from Anagram
while guess != hidden_word:
    if tries == 4:          # 4 attempts to say actual color from anagram
        print "You failed to guess in time!"
        print "The word was", hidden_word
        option_flag = True
        break
    else:
        if guess == hidden_word:
            print("Oh! You guessed it! The hidden word was", hidden_word)
            print("And it only took you", tries, "tries!\n")
            option_flag = True
            break
        else:
            tries += 1
            guess = raw_input("Guess the word: ")
            word_clue = clue(hidden_word, guess)
            print word_clue

if not option_flag:
    print "Oh! You guessed it! TheHidden word was: ", hidden_word
